vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlight" })

vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })

vim.keymap.set("n", "<leader>e", "<cmd>Neotree toggle reveal dir=./<cr>", { desc = "Toggle Neo-tree (Root)" })
vim.keymap.set("n", "<leader>ge", "<cmd>Neotree git_status<cr>", { desc = "Neo-tree Git Status" })
vim.keymap.set("n", "<leader>be", "<cmd>Neotree buffers<cr>", { desc = "Neo-tree Buffers" })
vim.keymap.set("n", "<leader>bn", "<cmd>enew<cr>", { desc = "Buffers: New" })
vim.keymap.set("n", "<leader>bh", "<cmd>bprevious<cr>", { desc = "Buffers: Previous" })
vim.keymap.set("n", "<leader>bl", "<cmd>bnext<cr>", { desc = "Buffers: Next" })
vim.keymap.set("n", "<leader>bc", function() Snacks.bufdelete() end, { desc = "Buffers: Close" })
vim.keymap.set("n", "<leader>oo", "<cmd>OverseerOpen<cr>", { desc = "Tasks: Open" })
vim.keymap.set("n", "<leader>oO", "<cmd>OverseerToggle<cr>", { desc = "Tasks: Toggle" })
vim.keymap.set("n", "<leader>or", "<cmd>OverseerRun<cr>", { desc = "Tasks: Run" })
vim.keymap.set("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Trouble: Workspace Diagnostics" })
vim.keymap.set("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Trouble: Buffer Diagnostics" })
vim.keymap.set("n", "<leader>xe", "<cmd>Trouble diagnostics toggle filter.severity=vim.diagnostic.severity.ERROR<cr>", { desc = "Trouble: Workspace Errors" })
vim.keymap.set("n", "<leader>xE", "<cmd>Trouble diagnostics toggle filter.buf=0 filter.severity=vim.diagnostic.severity.ERROR<cr>", { desc = "Trouble: Buffer Errors" })
vim.keymap.set("n", "<leader>xq", "<cmd>Trouble quickfix toggle<cr>", { desc = "Trouble: Quickfix" })
vim.keymap.set("n", "<leader>xl", "<cmd>Trouble loclist toggle<cr>", { desc = "Trouble: Location List" })
vim.keymap.set("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", { desc = "Trouble: Symbols" })
vim.keymap.set("n", "<leader>xr", "<cmd>Trouble lsp_references toggle focus=false<cr>", { desc = "Trouble: References" })
vim.keymap.set("n", "<leader>xd", "<cmd>Trouble lsp_definitions toggle focus=false<cr>", { desc = "Trouble: Definitions" })
vim.keymap.set("n", "<leader>sr", function()
	require("spectre").open({
		search_text = vim.fn.expand("<cword>"),
	})
end, { desc = "Search/Replace: Project" })
vim.keymap.set("n", "<leader>sR", function()
	require("spectre").open_file_search({
		select_word = true,
	})
end, { desc = "Search/Replace: Current File" })
vim.keymap.set("v", "<leader>sw", function()
	require("spectre").open_visual({
		select_word = true,
	})
end, { desc = "Search/Replace: Visual Selection" })
vim.keymap.set("n", "<leader>sA", function()
	require("spectre.actions").run_replace()
end, { desc = "Search/Replace: Apply" })
vim.keymap.set("n", "<leader>sl", function()
	require("spectre").resume_last_search()
end, { desc = "Search/Replace: Resume Last" })
vim.keymap.set("n", "<leader>gO", "<cmd>DiffviewOpen<cr>", { desc = "Git: Open Diffview" })
vim.keymap.set("n", "<leader>gC", "<cmd>DiffviewClose<cr>", { desc = "Git: Close Diffview" })
vim.keymap.set("n", "<leader>gF", "<cmd>DiffviewFileHistory<cr>", { desc = "Git: File History" })
vim.keymap.set("n", "<leader>gH", "<cmd>DiffviewFileHistory %<cr>", { desc = "Git: Current File History" })

vim.keymap.set("n", "<leader>ff", function() require("telescope.builtin").find_files() end, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", function() require("telescope.builtin").live_grep() end, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", function() require("telescope.builtin").buffers() end, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", function() require("telescope.builtin").help_tags() end, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>pp", function()
	require("telescope").extensions.project.project({ hide_workspace = true })
end, { desc = "Projects: Pick project" })
vim.keymap.set("n", "<leader>pf", "<cmd>Telescope frecency workspace=CWD<cr>", { desc = "Projects: Frecent files" })
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format buffer" })

vim.keymap.set("n", "<leader>tr", function() require("neotest").run.run() end, { desc = "Tests: Run nearest" })
vim.keymap.set("n", "<leader>tf", function()
	require("neotest").run.run(vim.fn.expand("%"))
end, { desc = "Tests: Run file" })
vim.keymap.set("n", "<leader>ts", function()
	require("neotest").run.run(vim.fn.getcwd())
end, { desc = "Tests: Run suite" })
vim.keymap.set("n", "<leader>td", function()
	require("neotest").run.run({ strategy = "dap" })
end, { desc = "Tests: Debug nearest" })
vim.keymap.set("n", "<leader>tt", function() require("neotest").run.stop() end, { desc = "Tests: Stop" })
vim.keymap.set("n", "<leader>to", function() require("neotest").output.open() end, { desc = "Tests: Output" })
vim.keymap.set("n", "<leader>tO", function() require("neotest").output_panel.toggle() end, { desc = "Tests: Output Panel" })
vim.keymap.set("n", "<leader>tS", function() require("neotest").summary.toggle() end, { desc = "Tests: Summary" })

vim.keymap.set("n", "<leader>db", function() require("dap").toggle_breakpoint() end, { desc = "Debug: Toggle Breakpoint" })
vim.keymap.set("n", "<leader>dB", function()
	require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Debug: Conditional Breakpoint" })
vim.keymap.set("n", "<leader>dc", function() require("dap").continue() end, { desc = "Debug: Continue" })
vim.keymap.set("n", "<leader>dr", function() require("dap").repl.open() end, { desc = "Debug: Open REPL" })
vim.keymap.set("n", "<leader>du", function() require("dapui").toggle() end, { desc = "Debug: Toggle UI" })
vim.keymap.set("n", "<leader>dt", function() require("dap").terminate() end, { desc = "Debug: Terminate" })
vim.keymap.set("n", "<leader>di", function() require("dap").step_into() end, { desc = "Debug: Step Into" })
vim.keymap.set("n", "<leader>do", function() require("dap").step_over() end, { desc = "Debug: Step Over" })
vim.keymap.set("n", "<leader>dO", function() require("dap").step_out() end, { desc = "Debug: Step Out" })
vim.keymap.set("n", "<leader>dl", function() require("dap").run_last() end, { desc = "Debug: Run Last" })



-- Cheatsheet split window shortcuts
vim.keymap.set("n", "<leader>cm", "<cmd>vsplit ~/.config/nvim/cheatsheet_motion.md<cr>", { desc = "Cheatsheet: Vim Motions" })
vim.keymap.set("n", "<leader>cp", "<cmd>vsplit ~/.config/nvim/cheatsheet_plugins.md<cr>", { desc = "Cheatsheet: Plugins" })
