vim.keymap.set("n", "<leader>e", "<cmd>Neotree toggle<cr>", { desc = "Toggle Neo-tree (Root)" })
vim.keymap.set("n", "<leader>E", "<cmd>Neotree toggle dir=%:p:h<cr>", { desc = "Toggle Neo-tree (CWD)" })
vim.keymap.set("n", "<leader>ge", "<cmd>Neotree git_status<cr>", { desc = "Neo-tree Git Status" })
vim.keymap.set("n", "<leader>be", "<cmd>Neotree buffers<cr>", { desc = "Neo-tree Buffers" })
vim.keymap.set("n", "<leader>bn", "<cmd>enew<cr>", { desc = "Buffers: New" })
vim.keymap.set("n", "<leader>bh", "<cmd>BufferPrevious<cr>", { desc = "Buffers: Previous" })
vim.keymap.set("n", "<leader>bl", "<cmd>BufferNext<cr>", { desc = "Buffers: Next" })
vim.keymap.set("n", "<leader>bc", "<cmd>BufferClose<cr>", { desc = "Buffers: Close" })
vim.keymap.set("n", "<leader>ot", "<cmd>ToggleTerm<cr>", { desc = "Terminal: Toggle" })
vim.keymap.set("n", "<leader>oo", "<cmd>OverseerOpen<cr>", { desc = "Tasks: Open" })
vim.keymap.set("n", "<leader>oO", "<cmd>OverseerToggle<cr>", { desc = "Tasks: Toggle" })
vim.keymap.set("n", "<leader>or", "<cmd>OverseerRun<cr>", { desc = "Tasks: Run" })
vim.keymap.set("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Trouble: Workspace Diagnostics" })
vim.keymap.set("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Trouble: Buffer Diagnostics" })
vim.keymap.set("n", "<leader>xe", "<cmd>Trouble diagnostics toggle filter.severity=vim.diagnostic.severity.ERROR<cr>", { desc = "Trouble: Workspace Errors" })
vim.keymap.set("n", "<leader>xE", "<cmd>Trouble diagnostics toggle filter.buf=0 filter.severity=vim.diagnostic.severity.ERROR<cr>", { desc = "Trouble: Buffer Errors" })
vim.keymap.set("n", "<leader>xq", "<cmd>Trouble quickfix toggle<cr>", { desc = "Trouble: Quickfix" })
vim.keymap.set("n", "<leader>xl", "<cmd>Trouble loclist toggle<cr>", { desc = "Trouble: Location List" })
vim.keymap.set("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", { desc = "Trouble: Symbols" })
vim.keymap.set("n", "<leader>xr", "<cmd>Trouble lsp_references toggle focus=false<cr>", { desc = "Trouble: References" })
vim.keymap.set("n", "<leader>xd", "<cmd>Trouble lsp_definitions toggle focus=false<cr>", { desc = "Trouble: Definitions" })
vim.keymap.set("n", "<leader>sr", function()
	require("spectre").open({
		search_text = vim.fn.expand("<cword>"),
	})
end, { desc = "Search/Replace: Project" })
vim.keymap.set("n", "<leader>sR", function()
	require("spectre").open_file_search({
		select_word = true,
	})
end, { desc = "Search/Replace: Current File" })
vim.keymap.set("v", "<leader>sw", function()
	require("spectre").open_visual({
		select_word = true,
	})
end, { desc = "Search/Replace: Visual Selection" })
vim.keymap.set("n", "<leader>sA", function()
	require("spectre.actions").run_replace()
end, { desc = "Search/Replace: Apply" })
vim.keymap.set("n", "<leader>sl", function()
	require("spectre").resume_last_search()
end, { desc = "Search/Replace: Resume Last" })
vim.keymap.set("n", "<leader>gg", "<cmd>Neogit<cr>", { desc = "Git: Neogit" })
vim.keymap.set("n", "<leader>gO", "<cmd>DiffviewOpen<cr>", { desc = "Git: Open Diffview" })
vim.keymap.set("n", "<leader>gC", "<cmd>DiffviewClose<cr>", { desc = "Git: Close Diffview" })
vim.keymap.set("n", "<leader>gF", "<cmd>DiffviewFileHistory<cr>", { desc = "Git: File History" })
vim.keymap.set("n", "<leader>gH", "<cmd>DiffviewFileHistory %<cr>", { desc = "Git: Current File History" })
vim.keymap.set("n", "<leader>gf", "<cmd>Git<cr>", { desc = "Git: Status (Fugitive)" })
vim.keymap.set("n", "<leader>gB", "<cmd>Git blame<cr>", { desc = "Git: Blame (Fugitive)" })

local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "<leader>pp", "<cmd>Telescope project<cr>", { desc = "Projects: Pick project" })
vim.keymap.set("n", "<leader>pf", "<cmd>Telescope frecency workspace=CWD<cr>", { desc = "Projects: Frecent files" })
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format buffer" })

local neotest = require("neotest")
vim.keymap.set("n", "<leader>tr", neotest.run.run, { desc = "Tests: Run nearest" })
vim.keymap.set("n", "<leader>tf", function()
	neotest.run.run(vim.fn.expand("%"))
end, { desc = "Tests: Run file" })
vim.keymap.set("n", "<leader>ts", function()
	neotest.run.run(vim.fn.getcwd())
end, { desc = "Tests: Run suite" })
vim.keymap.set("n", "<leader>td", function()
	neotest.run.run({ strategy = "dap" })
end, { desc = "Tests: Debug nearest" })
vim.keymap.set("n", "<leader>tt", neotest.run.stop, { desc = "Tests: Stop" })
vim.keymap.set("n", "<leader>to", neotest.output.open, { desc = "Tests: Output" })
vim.keymap.set("n", "<leader>tO", neotest.output_panel.toggle, { desc = "Tests: Output Panel" })
vim.keymap.set("n", "<leader>tS", neotest.summary.toggle, { desc = "Tests: Summary" })

local dap = require("dap")
local dapui = require("dapui")

vim.keymap.set("n", "<leader>db", dap.toggle_breakpoint, { desc = "Debug: Toggle Breakpoint" })
vim.keymap.set("n", "<leader>dB", function()
	dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Debug: Conditional Breakpoint" })
vim.keymap.set("n", "<leader>dc", dap.continue, { desc = "Debug: Continue" })
vim.keymap.set("n", "<leader>dr", dap.repl.open, { desc = "Debug: Open REPL" })
vim.keymap.set("n", "<leader>du", dapui.toggle, { desc = "Debug: Toggle UI" })
vim.keymap.set("n", "<leader>dt", dap.terminate, { desc = "Debug: Terminate" })
vim.keymap.set("n", "<leader>di", dap.step_into, { desc = "Debug: Step Into" })
vim.keymap.set("n", "<leader>do", dap.step_over, { desc = "Debug: Step Over" })
vim.keymap.set("n", "<leader>dO", dap.step_out, { desc = "Debug: Step Out" })
vim.keymap.set("n", "<leader>dl", dap.run_last, { desc = "Debug: Run Last" })

vim.api.nvim_create_autocmd("LspAttach", {
	group = vim.api.nvim_create_augroup("UserLspConfig", {}),
	callback = function(ev)
		local map = function(keys, func, desc)
			vim.keymap.set("n", keys, func, { buffer = ev.buf, desc = "LSP: " .. desc })
		end

		map("gd", vim.lsp.buf.definition, "Goto Definition")
		map("gD", vim.lsp.buf.declaration, "Goto Declaration")
		map("gr", vim.lsp.buf.references, "Goto References")
		map("gI", vim.lsp.buf.implementation, "Goto Implementation")
		map("gy", vim.lsp.buf.type_definition, "Type Definition")

		map("K", vim.lsp.buf.hover, "Hover Documentation")
		map("<C-k>", vim.lsp.buf.signature_help, "Signature Help")
		map("<leader>rn", vim.lsp.buf.rename, "Rename Symbol")
		map("<leader>ca", vim.lsp.buf.code_action, "Code Action")

		map("<leader>cd", vim.diagnostic.open_float, "Line Diagnostics")
		map("[d", vim.diagnostic.goto_prev, "Previous Diagnostic")
		map("]d", vim.diagnostic.goto_next, "Next Diagnostic")
	end,
})
